- name: Reload firewall
  ansible.builtin.systemd:
    name: firewalld
    state: reloaded
  become: true

- name: Reload nginx
  ansible.builtin.systemd:
    name: nginx
    state: reloaded
  become: true
