# App server infos

IP_app: 10.102.20.12
app_listen_port: 30000

authorized_IPs:
  - "{{ IP_ansible_host }}"
  - "{{ IP_router }}"

authorized_ports:
  - 443/tcp

packages_needed:
  - openssh-server
  - vi
  - nginx
  - tar
