# App server infos

IP_app: 10.102.20.12
app_listen_port: 30000

authorized_IP:
  - "{{ IP_ansible_host }}"
  - "{{ IP_router }}"
  - "{{ IP_bastion }}"

common_packages:
  - openssh-server
  - vi
  - nginx
