---
- name: Config NFS_server
  hosts: nfsserver
  roles:
    - common
    - nfs-server

- name: Config App server
  hosts: appserver
  roles:
    - common
    - nfs-client
    - app

- name: Config Reverse_proxy
  hosts: reverseproxy
  roles:
    - common
    - ssl_setup
    - nginx_rproxy
    - ngrok
